### PR TITLE
Extracted CustomSlide and Utils

### PR DESCRIPTION
**Pull request by joedmru**
1. Extracted CustomSlide and Utils
2. Tweak wordings and code style;

### CODE REVIEW

**Comment by vit9696** [comment]
Hi,
Thanks for continuing the uneasy refactoring process. I will comment right here to ease the communication.

Regarding structural changes:
- I think [boot-args](https://github.com/vit9696/AptioFixPkg/pull/3/files#diff-c2d78e80ba267f23a1cf55f44a9f4fe3R520) parsing should be done elsewhere. Just as you mentioned, it does not look right at the moment. Since we already have [the loaded image](https://github.com/vit9696/AptioFixPkg/blob/master/Platform/AptioMemoryFix/AptioMemoryFix.c#L122) protocol here, perhaps we could just make a separate function like LoadBootArguments? It is probably still not so perfect, but I'd say parsing -aptiodump and even slide is not really relevant to custom slide implementation. Whether slide exists in boot-args or not, could be the job of a caller to check.
- I think PrintSample2 is not really needed. Currently building with debug support will not really work fine, and the necessity of making a [dump of an overwritten ep](https://github.com/vit9696/AptioFixPkg/blob/a7ef9df04148648363f68eed95a88ac72ce2ce81/Platform/AptioMemoryFix/BootFixes.c#L202) is very low. Just remove it, in my opinion.

Regarding some minor style-related stuff:
- edk2 seems to like to typedef and use upper case names for structs [link](https://github.com/tianocore/tianocore.github.io/wiki/Code-Style-C#UPPERCASE), and while we should not change imported types from XNU (like BootArgs1/BootArgs2), our own custom type (BootArguments) should probably be typedef'ed and renamed to something like BOOT_ARGS or BOOT_ARGUMENTS. That also includes the [fwd declaration](https://github.com/vit9696/AptioFixPkg/pull/3/files#diff-662c40d9e24d073b783dd3e27f3a9330R9) part, I think it can be just removed.
- I am not sure if that is mentioned anywhere, but static variables are meant to be written with m (module?) prefix, and globals should be g (global). Changing it will be nice.

I guess there are places for improvement, but once the above is resolved, and the code works fine, I will be ok to merge it.

I kind of wanted to mention comments, and then I realised that edk2 guys do not even understand how to format them. I guess for now it is more important to review their contents and add more of them in tricky places, than to attempt to fix the style…

@Download-Fritz regarding the comments, you seem to know more people from edk2 than I do. Perhaps you could explain this? The [majority of their code](https://github.com/tianocore/edk2/blob/master/MdePkg/Library/BasePrintLib/PrintLibInternal.c#L138) including even new portions contains a starting empty // and their [standard](https://github.com/tianocore-docs/edk2-CCodingStandardsSpecification/blob/master/6_documenting_software/62_comments.md#623-avoid-comments-where-the-opening-comment-characters-are-alone-on-a-line) says it is forbidden. They also forbid multiline comments with two slashes, but just a [random new commit](https://github.com/tianocore/edk2/commit/6b86f6f336b9ccfdc27b718100c31b2aed5d7bb1) shows that they are fine with it.

**Comment by mhaeuser** [comment]
@vit9696 Honestly, sticking to the C code style document is pointless, no code in the entire repo is formated to follow its rules. I'm not quite sure why it's around.
I use the same comment style as they do in their actual sources because it looks kind of 'clean'. What's your preference?

**Comment by vit9696** [comment]
Well, ok, after some short discussion in private I kind of get the point: wherever M$ goes, bad things happen. I guess if edk2 guys do not follow it in practice, then we should probably stick to what they actually do, and then it means:
```
//
// Something
// Something
//
```

**Comment by vit9696** [comment]
Thanks! I made some fixes and cleanups before merging (https://github.com/vit9696/AptioFixPkg/pull/3/commits/3631d3e8e3779f564ec50cb2a19c38891bea9a5a and https://github.com/vit9696/AptioFixPkg/pull/3/commits/5fa654ab15b79ac3507050ae1f89719d66d52d9d), let me know if there are any issues.

**Pull request merged**
